### ISSUE TITLE
Reproduce the results in paper

### ISSUE THREAD

**Issue by Aidenzich** [YuWang-1024/ContrastVAE#1]
Hello, thank you for your great work. However, I would like to ask how to reproduce the beauty dataset results in the original paper.

I use the hyperparameters mentioned in the paper, but the highest NDCG@10 is 0.01848... which is quite different from the paper's results.

**Comment by YuWang-1024** [comment]
Hi, thanks for your interest, the parameters in the paper lack some details, I just retried these parameters with similar results: python main.py --latent_contrastive_learning  --data_name=Beauty --latent_clr_weight=0.6 --reparam_dropout_rate=0.1 --lr=0.001 --hidden_size=128 --max_seq_length=50 --hidden_dropout_prob=0.3 --num_hidden_layers=1 --weight_decay=0.0 --num_attention_heads=4 --model_name=VAGRec --attention_probs_dropout_prob=0.0 --anneal_cap=0.2 --total_annealing_step=10000, could you please try out this model?

**Comment by Aidenzich** [comment]
> 

Thank you for your kind response! I am training my model, and I will update my state as soon as testing is complete and close this issue.

**Comment by Aidenzich** [comment]
Nice, I got similar results in the paper, thank you for your patience and amazing work again!
